version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_os_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: os_db
      MYSQL_ROOT_PASSWORD: "H3@rtDB@#00"
      MYSQL_USER: os_db_user
      MYSQL_PASSWORD: "H3@rtDB@#00"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql